# INTRO NUMPY

### Syaima Radestya - SESI 4

In [2]:
# contoh operasi penjumlahan vektor
# menggunakan list

a = [1, 3, 5, 7]
b = [2, 4, 8, 6]

def jumlah(a, b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

In [4]:
a + b

[1, 3, 5, 7, 2, 4, 8, 6]

In [5]:
# tipe data dari numpy -> np.array
import numpy as np

a = [1, 3, 5, 7]
b = [2, 4, 8, 6]
np_a = np.array(a)
np_b = np.array(b)

In [7]:
np_a - np_b

array([-1, -1, -3,  1])

In [8]:
np_a * np_b

array([ 2, 12, 40, 42])

In [10]:
# contoh array

a1d = [1,2,3,4,5]
a1d = np.array(a1d)
a1d

array([1, 2, 3, 4, 5])

In [11]:
a2d = [[4,8],[3,9],[7,2]]
a2d = np.array(a2d)
a2d

array([[4, 8],
       [3, 9],
       [7, 2]])

In [14]:
# error jika tidak memiliki jumlah elemen yang sama
a2d = [[1,4],[2,9,5],[3,7]]
a2d = np.array(a2d)
a2d

C:\Users\User\AppData\Local\Temp\ipykernel_14752\1783949764.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2d = np.array(a2d)


array([list([1, 4]), list([2, 9, 5]), list([3, 7])], dtype=object)

In [21]:
a = [1,2,3,4,2.7, "Hi"]
a

[1, 2, 3, 4, 2.7, 'Hi']

In [22]:
a = np.array(a)
a

array(['1', '2', '3', '4', '2.7', 'Hi'], dtype='<U32')

In [26]:
A = [[1,2],[3,4],[9,7]]
A = np.array(A)
A

array([[1, 2],
       [3, 4],
       [9, 7]])

In [27]:
A[2,1]

7

In [28]:
A[2][1]

7

In [29]:
# memanggil baris
A[1]

array([3, 4])

In [30]:
A[1, :]

array([3, 4])

In [31]:
# memanggil kolom
A[:, 0]

array([1, 3, 9])

In [33]:
# special array
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.arange(1,5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [47]:
A = [[3,5],[4,8],[7,9], [6,1]]
A = np.array(A)
A

array([[3, 5],
       [4, 8],
       [7, 9],
       [6, 1]])

In [48]:
A.ndim

2

In [49]:
A.shape

(4, 2)

In [50]:
A.size

8

In [53]:
a = [2,3,1,6,5,7,5,6,4,8]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6, 4, 8])

In [55]:
a.reshape((2,5))

array([[2, 3, 1, 6, 5],
       [7, 5, 6, 4, 8]])

In [56]:
a.reshape((2,5)).T

array([[2, 7],
       [3, 5],
       [1, 6],
       [6, 4],
       [5, 8]])

In [60]:
a = [2,3,1,6,5,7,5,6,9,4,8]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6, 9, 4, 8])

In [61]:
a[np.newaxis]

array([[2, 3, 1, 6, 5, 7, 5, 6, 9, 4, 8]])

In [62]:
a[:,np.newaxis]

array([[2],
       [3],
       [1],
       [6],
       [5],
       [7],
       [5],
       [6],
       [9],
       [4],
       [8]])

In [63]:
a

array([2, 3, 1, 6, 5, 7, 5, 6, 9, 4, 8])

In [64]:
np.expand_dims(a, axis=1).shape

(11, 1)

In [65]:
a.shape

(11,)

#### Querying

In [67]:
mat = [[5,4,3,8,2], [4,6,3,7,4], [1,6,4,5,6], [8,5,1,0,3]]
mat = np.array(mat)
mat

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6],
       [8, 5, 1, 0, 3]])

In [74]:
mat[1:3, -2:]

array([[7, 4],
       [5, 6]])

In [79]:
mat < 3

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True,  True, False]])

In [81]:
mat[mat < 3]

array([2, 1, 1, 0])

In [86]:
mahasiswa = np.array(['Nia', 'Ani', 'Jodi', 'Tiara'])
nilai = np.array([55.7, 75.3, 53.4, 84.2])

In [87]:
nilai < 60

array([ True, False,  True, False])

In [88]:
kondisi = nilai < 60
mahasiswa[kondisi]

array(['Nia', 'Jodi'], dtype='<U5')

In [89]:
A = np.array([[1,2], [3,4]])
B = np.array([[6,5], [2,7]])
c = np.array([1,2])

In [91]:
A

array([[1, 2],
       [3, 4]])

In [92]:
B

array([[6, 5],
       [2, 7]])

In [93]:
A*B

array([[ 6, 10],
       [ 6, 28]])

In [94]:
A.mean(axis=0)

array([2., 3.])

In [95]:
np.random.random((2,5))

array([[0.20044909, 0.070841  , 0.81434684, 0.97215502, 0.11281807],
       [0.70411246, 0.4250852 , 0.85458914, 0.99545793, 0.80941815]])

In [99]:
C = np.arange(0,20)
C = C.reshape((4,5))

In [100]:
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [102]:
C.reshape((10,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])