# SESI 9 - Descriptive Statistics

### Syaima Radestya
PYTN-KS-010

## Ringkasan
***
**Descriptive statistic**, yaitu melibatkan meringkas/summarizing dan mengatur data sehingga dapat dengan mudah dipahami. biasanya mendeskripsikan data dalam sampel. Membantu kita memahami data dan bagian yang sangat penting dari machine learning. Types of Descriptive Statistic dipecah menjadi 2 kategori, yaitu *Measures of central tendency dan Measures of variability (spread)*. <br> <br>
**Population and Samples**, populasi yaitu sekumpulan dr semua elemen/item yg kita minati. subset populasi disebut sampel.
Outliers, yaitu titik data yg berbeda secara signifikan dari sebagian besar data yang diambil dari sampel/populasi. penyebab outliers atau pencilan yaitu: <br>
•	natural variation of data <br>
•	change in the behaviour of the observed system <br>
•	Errors in data collection <br> <br>
**Measure of Central Tendency**, yaitu mengacu pada gagasan bahwa ada suatu bilangan yang paling baik untuk meringkas seluruh rangkaian pengukuran, sebuah bilangan yang dalam beberapa hal merupakan “central” dari himpunan tersebut. <br> <br>
**Mean / Average**, yaitu central tendency dari data, angka diantara seluruh data tersebar. Rata-rata dihitung dengan jumlah semua nilai, dibagi dengan jumlah nilai. <br>
mean = (jumlah semua nilai) / (jumlah nilai) <br> <br>
**Median**, yaitu nilai yang membagi data dalam 2 bagian yang sama yaitu jumlah suku di sisi kanannya sama dengan jumlah suku di sisi kirinya saat data disusun dalam urutan naik atau turun. Median biasa disebut persentil ke-50. Median lebih cocok untuk melaporkan data kita karena lebih sedikit dipengaruhi oleh outliers dan skewed data daripada average. <br> <br>
**Mode**, yaitu nilai yang muncul secara maksimum dalam kumpulan data, nilai yang memiliki frekuensi tertinggi. Modus adalah nilai/kategori yang paling sering muncul dalam data. <br> <br>
**Measure of Spread / Dispersion**, mengacu pada gagasan variabilitas dalam data. juga digunakan untuk mengukur seberapa 'bagus' mean merepresentasikan kumpulan data. <br> <br>
**Standard Deviation / Simpangan Baku**, yaitu pengukuran jarak rata-rata antara setiap besaran dan mean. Artinya, bagaimana data disebarkan/seberapa tersebar data dari mean. Standar deviasi yang rendah menunjukkan bahwa titik data cenderung mendekati rata-rata kumpulan data, sedangkan standar deviasi yang tinggi menunjukkan bahwa titik data tersebar di nilai yang lebih luas. <br> <br>
**Mean Deviation / Mean Absolute Deviation**, yaitu rata-rata perbedaan absolut antara setiap nilai dalam satu sel nilai, dan rata-rata semua nilai dari set itu. <br> <br>
**Variance**, yaitu kuadrat jarak rata-rata antara setiap kuantitas dan mean. atau kuadrat dari standar deviasi. Varians dihitung dengan mencari selisih antara setiap titik data dan mean, mengkuadratkan, menjumlahkan, kemudian mengambil rata-rata dari angka-angka itu. <br> <br>
**Range**, yaitu perbedaan antara nilai terendah dan tertinggi <br> <br>
**Percentile**, yaitu cara untuk merepresentasikan posisi suatu nilai dalam kumpulan data. Untuk menghitunnya, nilai dalam kumpulan data harus selalu dalam urutan ascending/menaik. <br> <br>
**Quartiles**, yaitu nilai yang membagi data menjadi beberapa quarters jika data diurutkan dalam urutan ascending/menaik. <br> <br>
**Skewness**, yaitu ukuran asimetri distribusi probabilitas dari real-valued random variabel tentang meannya. Nilai kemiringan bisa positif/negatif/undefined. Negative skew (distribusi miring ke kiri), positive skew (distribusi miring ke kanan), symmetricl distribution (pas di tengah) <br> <br>
**Kurtosis**, yaitu ukuran apakah data bersifat hevy-tailed (banyak outlier) atau light-tailed (kurang outlier) relatif terhadap distribusi normal. Ada 3 tipe dari kurtosis: <br>
1. *Mesokurtic* : distribusi yang memiliki kurtosis serupa dengan kurtosis bedistribusi normal, yaitu nol
2. *Leptokuric* : distribusi yang memiliki kurtosis lebih besar drpd distribusi mesokurtik.
3. *Playkurtic* : distribusi yang memiliki kurtosis lebih rendah dari distribsi mesokurtik. <br>

perbedaannya dengan *skewness* yaitu *skewness* mengacu pada tingkat simetri, sedangkan kurtosis mengacu pada tingkat keberadaan pencilan dalam distribusi
Correlation, yaitu teknik statistik yang dapat menunjukkan apakah dan seberapa kuat variabel terkait. hasil utama korelasi disebut correlation coefficient (atau 'r'). Semakin dekan r ke +1 atau -1, semakin erat hubungan kedua variabel tersebut. jika r mendekati 0, maka tak ada hubungan antar variabel. <br>
Jika r positif, berarti semakin besar satu variabel, variabel lainnya semakin besar. Jika r negatif, berarti semakin besar satu variabel, variabel yang lain akan semakin kecil.


## Practice in Python
***

In [4]:
#import semua packages yg diperlukan
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [5]:
#buat bbrp data utk dikerjakan
x =[8.0, 1, 2.5, 7, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 7, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 7, 28.0]
[8.0, 1, 2.5, nan, 7, 28.0]


In [6]:
#buat objek np.array & pd.Series yg sesuai dgn x & x_with_nan
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  7.  28. ]
[ 8.   1.   2.5  nan  7.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     7.0
5    28.0
dtype: float64


## Measures of Central Tendency
***

### Mean

In [7]:
#menghitun mean menggunakan sum() dan len()
mean_ = sum(x) / len(x)
mean_

9.3

In [8]:
#jika menggunakan numpy
mean_ = np.mean(y)
mean_

9.3

In [9]:
#mean pada pd.Series
mean_ = z.mean()
mean_

9.3

In [10]:
# Weighted Mean
0.2*2+0.5*6+0.5*8

7.4

In [20]:
# Implementasi
t = [1, 1, 1, 1, 1]
s = [1, 2, 3, 4, 5]

wmean = sum(t[i] * s[i] for i in range (len(s))) / sum(t)
print(wmean)

wmean = sum(s_ * t_ for (s_, t_) in zip(s,t)) / sum(t)
print(wmean)

3.0
3.0


### Median

In [21]:
#implementasi
n = len(x)
if n % 2:
    median_ =sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5*n)
    median_ = 0.5*(x_ord[index-1]+x_ord[index])
    
median_

7

In [22]:
x

[8.0, 1, 2.5, 7, 28.0]

In [23]:
statistics.median_low(x[:-1])

2.5

In [24]:
statistics.median_high(x[:-1])

7

### Mode

In [29]:
#implementasi
u = [2,3,5,8,5]
v = [12,15,12,15,21,15,12]

mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

5

In [30]:
# dgn statistics.mode()
mode_ = statistics.mode(u)
mode_

5

### Measures of Variability

In [33]:
#implementasi
n = len(x)

mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / (n-1)
var_

117.95

In [32]:
#memanggil fungsi statistics.variance()
var_ = statistics.variance(x)
var_

117.95

In [34]:
# dengan numpy
var_ = np.var(y, ddof=1)
var_

117.95

### Standard Deviatiom

In [35]:
#implementasi
std_ = var_**0.5
std_

10.86047881080756

In [36]:
y.std(ddof=1)

10.86047881080756

In [38]:
#dengan pd.Series yg mengabaikan nan (secara default)
z.std(ddof=1)

10.86047881080756

### Percentiles

In [39]:
#implementasi
x = [-2.0, -1.5, 0.5, 2.0, 8.0, 12.7, 21.0, 25.3, 41.0]

In [40]:
p = np.array(x)

In [42]:
# dengan numpy
np.percentile(p,5)

-1.8

In [43]:
np.percentile(p,95)

34.71999999999999

In [44]:
#menghitung persentil ke-25, ke-50, ke-75 sekaligus
np.percentile(p, [25,50,75])

array([ 0.5,  8. , 21. ])

## Measures of Correlation Between Pairs of Data
***

### Covarience

In [47]:
x=list(range(-10,11))
y=[0,2,2,2,2,3,3,6,7,4,7,6,6,9,4,5,5,10,11,12,14]
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)

In [48]:
n=len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n-1))
cov_xy

19.95

In [49]:
# dengan numpy
cov_matrix = np.cov(x_, y_)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [50]:
x_.var(ddof=1)

38.5

In [51]:
y_.var(ddof=1)

13.914285714285711

### Correlation Coefficient

In [52]:
#implementasi
var_x = sum((item -mean_x)**2 for item in x) / (n-1)
var_y = sum((item -mean_y)**2 for item in y) / (n-1)
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [53]:
# dengan scipy
r, p = scipy.stats.pearsonr(x_, y_)
r

0.861950005631606

In [54]:
p

5.122760847201171e-07

In [55]:
# dengan numpy
corr_matrix = np.corrcoef(x_, y_)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [56]:
r = corr_matrix[0,1]
r

0.8619500056316061